export const UPDATE_CUSTOMER_POPUP_STATE = "UPDATE_CUSTOMER_POPUP_STATE";
export const UPDATE_ADD_CUSTOMER_POPUP_STATE =
  "UPDATE_ADD_CUSTOMER_POPUP_STATE";
export const UPDATE_ADD_FIELD_POPUP_STATE = "UPDATE_ADD_FIELD_POPUP_STATE";
